# Generated by Django 5.2.6 on 2025-11-09 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_extracted_text_document_uploaded_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='studentprofile', serialize=False, to='core.student')),
                ('highest_percentage', models.FloatField(blank=True, null=True)),
                ('degrees', models.JSONField(blank=True, default=list)),
                ('annual_income', models.IntegerField(blank=True, null=True)),
                ('verified_skills', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
